//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Wrappers.IO
{
  
  
  /// <summary>Listens to the file system change notifications and raises events when a directory, or file in a directory, changes.</summary>
  /// <filterpriority>2</filterpriority>
  public class FileSystemWatcherWrapper : Wrapperator.Interfaces.IO.IFileSystemWatcher
  {
    
    internal System.IO.FileSystemWatcher FileSystemWatcher { get; private set; }

    
    internal FileSystemWatcherWrapper(System.IO.FileSystemWatcher fileSystemWatcher)
    {
      FileSystemWatcher = fileSystemWatcher;
    }
    
    public System.IO.NotifyFilters NotifyFilter
    {
      get
      {
        return FileSystemWatcher.NotifyFilter;
      }
      set
      {
        FileSystemWatcher.NotifyFilter = value;
      }
    }
    
    public bool EnableRaisingEvents
    {
      get
      {
        return FileSystemWatcher.EnableRaisingEvents;
      }
      set
      {
        FileSystemWatcher.EnableRaisingEvents = value;
      }
    }
    
    public string Filter
    {
      get
      {
        return FileSystemWatcher.Filter;
      }
      set
      {
        FileSystemWatcher.Filter = value;
      }
    }
    
    public bool IncludeSubdirectories
    {
      get
      {
        return FileSystemWatcher.IncludeSubdirectories;
      }
      set
      {
        FileSystemWatcher.IncludeSubdirectories = value;
      }
    }
    
    public int InternalBufferSize
    {
      get
      {
        return FileSystemWatcher.InternalBufferSize;
      }
      set
      {
        FileSystemWatcher.InternalBufferSize = value;
      }
    }
    
    public string Path
    {
      get
      {
        return FileSystemWatcher.Path;
      }
      set
      {
        FileSystemWatcher.Path = value;
      }
    }
    
    public System.ComponentModel.ISite Site
    {
      get
      {
        return FileSystemWatcher.Site;
      }
      set
      {
        FileSystemWatcher.Site = value;
      }
    }
    
    public System.ComponentModel.ISynchronizeInvoke SynchronizingObject
    {
      get
      {
        return FileSystemWatcher.SynchronizingObject;
      }
      set
      {
        FileSystemWatcher.SynchronizingObject = value;
      }
    }
    
    public System.ComponentModel.IContainer Container
    {
      get
      {
        return FileSystemWatcher.Container;
      }
    }
    
    /// <summary>Begins the initialization of a <see cref="T:System.IO.FileSystemWatcher" /> used on a form or used by another component. The initialization occurs at run time.</summary>
    /// <filterpriority>2</filterpriority>
    public void BeginInit()
    {
      FileSystemWatcher.BeginInit();
    }
    
    /// <summary>Ends the initialization of a <see cref="T:System.IO.FileSystemWatcher" /> used on a form or used by another component. The initialization occurs at run time.</summary>
    /// <filterpriority>2</filterpriority>
    public void EndInit()
    {
      FileSystemWatcher.EndInit();
    }
    
    /// <summary>A synchronous method that returns a structure that contains specific information on the change that occurred, given the type of change you want to monitor.</summary>
    /// <returns>A <see cref="T:System.IO.WaitForChangedResult" /> that contains specific information on the change that occurred.</returns>
    /// <param name="changeType">The <see cref="T:System.IO.WatcherChangeTypes" /> to watch for. </param>
    /// <filterpriority>2</filterpriority>
    public System.IO.WaitForChangedResult WaitForChanged(System.IO.WatcherChangeTypes changeType)
    {
      return FileSystemWatcher.WaitForChanged(changeType);
    }
    
    /// <summary>A synchronous method that returns a structure that contains specific information on the change that occurred, given the type of change you want to monitor and the time (in milliseconds) to wait before timing out.</summary>
    /// <returns>A <see cref="T:System.IO.WaitForChangedResult" /> that contains specific information on the change that occurred.</returns>
    /// <param name="changeType">The <see cref="T:System.IO.WatcherChangeTypes" /> to watch for. </param>
    /// <param name="timeout">The time (in milliseconds) to wait before timing out. </param>
    /// <filterpriority>2</filterpriority>
    public System.IO.WaitForChangedResult WaitForChanged(System.IO.WatcherChangeTypes changeType, int timeout)
    {
      return FileSystemWatcher.WaitForChanged(changeType, timeout);
    }
    
    /// <summary>Retrieves the current lifetime service object that controls the lifetime policy for this instance.</summary>
    /// <returns>An object of type <see cref="T:System.Runtime.Remoting.Lifetime.ILease" /> used to control the lifetime policy for this instance.</returns>
    /// <exception cref="T:System.Security.SecurityException">The immediate caller does not have infrastructure permission. </exception>
    /// <filterpriority>2</filterpriority>
    public object GetLifetimeService()
    {
      return FileSystemWatcher.GetLifetimeService();
    }
    
    /// <summary>Obtains a lifetime service object to control the lifetime policy for this instance.</summary>
    /// <returns>An object of type <see cref="T:System.Runtime.Remoting.Lifetime.ILease" /> used to control the lifetime policy for this instance. This is the current lifetime service object for this instance if one exists; otherwise, a new lifetime service object initialized to the value of the <see cref="P:System.Runtime.Remoting.Lifetime.LifetimeServices.LeaseManagerPollTime" /> property.</returns>
    /// <exception cref="T:System.Security.SecurityException">The immediate caller does not have infrastructure permission. </exception>
    /// <filterpriority>2</filterpriority>
    public object InitializeLifetimeService()
    {
      return FileSystemWatcher.InitializeLifetimeService();
    }
    
    /// <summary>Creates an object that contains all the relevant information required to generate a proxy used to communicate with a remote object.</summary>
    /// <returns>Information required to generate a proxy.</returns>
    /// <param name="requestedType">The <see cref="T:System.Type" /> of the object that the new <see cref="T:System.Runtime.Remoting.ObjRef" /> will reference. </param>
    /// <exception cref="T:System.Runtime.Remoting.RemotingException">This instance is not a valid remoting object. </exception>
    /// <exception cref="T:System.Security.SecurityException">The immediate caller does not have infrastructure permission. </exception>
    /// <filterpriority>2</filterpriority>
    public System.Runtime.Remoting.ObjRef CreateObjRef(Wrapperator.Interfaces.IType requestedType)
    {
      return FileSystemWatcher.CreateObjRef(requestedType == null ? default(System.Type) : ((Wrapperator.Wrappers.TypeWrapper)requestedType).Type);
    }
    
    public void Dispose()
    {
      this.Dispose(true);
      System.GC.SuppressFinalize(this);
    }
    
    protected virtual void Dispose(bool disposing)
    {
      if (disposing)
      {
        FileSystemWatcher.Dispose();
      }
    }
  }
}
