version: 1.0.{build}
branches:
  only:
  - master
  - develop
image: Visual Studio 2015
environment:
  NuGetApiKey:
    secure: Q2iw3AS2EBEcG4wVWDZY/ruR0Whvs50gTeCleO/uypdP7G7ajODYw030N3sOONtP
  GitHubToken:
    secure: Lp2YKeJITl6VZV0SSdpSrbnuPujRolIyat9yAIq7W3xNkSZ36PGrPwRMrPBK4V11
install:
- ps: git submodule update --init --recursive --quiet
build_script:
- ps: |       
    Push-Location "src"

    $Version = ./Shared/Build/Versioning.ps1
    $IsPreRelease = $env:APPVEYOR_REPO_BRANCH -ne "master"
    $PushNuGetPackages = $env:APPVEYOR_REPO_BRANCH -eq "master" -and $env:APPVEYOR_REPO_TAG -eq "true"

    ./Build.ps1 `
      -Mode "AppVeyor" `
      -Version $Version `
      -IsPreRelease $IsPreRelease `
      -Configuration "Release" `
      -CreateNuGetPackages $True `
      -PushNuGetPackages $PushNuGetPackages `
      -NuGetApiKey "$env:NuGetApiKey"

    Pop-Location
test: off