//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Wrappers.Reflection
{
  
  
  /// <summary>Describes an assembly's unique identity in full.</summary>
  public class AssemblyNameWrapper : Wrapperator.Interfaces.Reflection.IAssemblyName
  {
    
    internal System.Reflection.AssemblyName AssemblyName { get; private set; }

    
    public AssemblyNameWrapper(System.Reflection.AssemblyName assemblyName)
    {
      AssemblyName = assemblyName;
    }
    
    public string Name
    {
      get
      {
        return AssemblyName.Name;
      }
      set
      {
        AssemblyName.Name = value;
      }
    }
    
    public System.Version Version
    {
      get
      {
        return AssemblyName.Version;
      }
      set
      {
        AssemblyName.Version = value;
      }
    }
    
    public System.Globalization.CultureInfo CultureInfo
    {
      get
      {
        return AssemblyName.CultureInfo;
      }
      set
      {
        AssemblyName.CultureInfo = value;
      }
    }
    
    public string CodeBase
    {
      get
      {
        return AssemblyName.CodeBase;
      }
      set
      {
        AssemblyName.CodeBase = value;
      }
    }
    
    public string EscapedCodeBase
    {
      get
      {
        return AssemblyName.EscapedCodeBase;
      }
    }
    
    public System.Reflection.ProcessorArchitecture ProcessorArchitecture
    {
      get
      {
        return AssemblyName.ProcessorArchitecture;
      }
      set
      {
        AssemblyName.ProcessorArchitecture = value;
      }
    }
    
    public System.Reflection.AssemblyContentType ContentType
    {
      get
      {
        return AssemblyName.ContentType;
      }
      set
      {
        AssemblyName.ContentType = value;
      }
    }
    
    public System.Reflection.AssemblyNameFlags Flags
    {
      get
      {
        return AssemblyName.Flags;
      }
      set
      {
        AssemblyName.Flags = value;
      }
    }
    
    public System.Configuration.Assemblies.AssemblyHashAlgorithm HashAlgorithm
    {
      get
      {
        return AssemblyName.HashAlgorithm;
      }
      set
      {
        AssemblyName.HashAlgorithm = value;
      }
    }
    
    public System.Configuration.Assemblies.AssemblyVersionCompatibility VersionCompatibility
    {
      get
      {
        return AssemblyName.VersionCompatibility;
      }
      set
      {
        AssemblyName.VersionCompatibility = value;
      }
    }
    
    public System.Reflection.StrongNameKeyPair KeyPair
    {
      get
      {
        return AssemblyName.KeyPair;
      }
      set
      {
        AssemblyName.KeyPair = value;
      }
    }
    
    public string FullName
    {
      get
      {
        return AssemblyName.FullName;
      }
    }
    
    /// <summary>Makes a copy of this <see cref="T:System.Reflection.AssemblyName" /> object.</summary>
    /// <returns>An object that is a copy of this <see cref="T:System.Reflection.AssemblyName" /> object.</returns>
    public object Clone()
    {
      return AssemblyName.Clone();
    }
    
    /// <summary>Gets the public key of the assembly.</summary>
    /// <returns>A byte array that contains the public key of the assembly.</returns>
    /// <exception cref="T:System.Security.SecurityException">A public key was provided (for example, by using the <see cref="M:System.Reflection.AssemblyName.SetPublicKey(System.Byte[])" /> method), but no public key token was provided. </exception>
    public byte[] GetPublicKey()
    {
      return AssemblyName.GetPublicKey();
    }
    
    /// <summary>Sets the public key identifying the assembly.</summary>
    /// <param name="publicKey">A byte array containing the public key of the assembly. </param>
    public void SetPublicKey(byte[] publicKey)
    {
      AssemblyName.SetPublicKey(publicKey);
    }
    
    /// <summary>Gets the public key token, which is the last 8 bytes of the SHA-1 hash of the public key under which the application or assembly is signed.</summary>
    /// <returns>A byte array that contains the public key token.</returns>
    public byte[] GetPublicKeyToken()
    {
      return AssemblyName.GetPublicKeyToken();
    }
    
    /// <summary>Sets the public key token, which is the last 8 bytes of the SHA-1 hash of the public key under which the application or assembly is signed.</summary>
    /// <param name="publicKeyToken">A byte array containing the public key token of the assembly. </param>
    public void SetPublicKeyToken(byte[] publicKeyToken)
    {
      AssemblyName.SetPublicKeyToken(publicKeyToken);
    }
    
    /// <summary>Gets serialization information with all the data needed to recreate an instance of this AssemblyName.</summary>
    /// <param name="info">The object to be populated with serialization information. </param>
    /// <param name="context">The destination context of the serialization. </param>
    /// <exception cref="T:System.ArgumentNullException">
    ///  <paramref name="info" /> is null. </exception>
    public void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
    {
      AssemblyName.GetObjectData(info, context);
    }
    
    /// <summary>Implements the <see cref="T:System.Runtime.Serialization.ISerializable" /> interface and is called back by the deserialization event when deserialization is complete.</summary>
    /// <param name="sender">The source of the deserialization event. </param>
    public void OnDeserialization(object sender)
    {
      AssemblyName.OnDeserialization(sender);
    }
  }
}
