//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Interfaces.IO.Compression
{
  
  
  /// <summary>Provides methods and properties for compressing and decompressing streams by using the Deflate algorithm.</summary>
  public interface IDeflateStream : Wrapperator.Interfaces.IO.IStream
  {
    
    /// <summary>Provides access to the wrapped instance. Should not be used most of the time.</summary>
    System.IO.Compression.DeflateStream _DeflateStream
    {
      get;
    }
    
    Wrapperator.Interfaces.IO.IStream BaseStream
    {
      get;
    }
  }
}
