//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Wrappers.Configuration
{
  
  
  /// <summary>Encapsulates the context information that is associated with a <see cref="T:System.Configuration.ConfigurationElement" /> object. This class cannot be inherited.</summary>
  public class ContextInformationWrapper : Wrapperator.Interfaces.Configuration.IContextInformation
  {
    
    public System.Configuration.ContextInformation _ContextInformation { get; private set; }

    
    internal ContextInformationWrapper(System.Configuration.ContextInformation contextInformation)
    {
      _ContextInformation = contextInformation;
    }
    
    public object HostingContext
    {
      get
      {
        return _ContextInformation.HostingContext;
      }
    }
    
    public bool IsMachineLevel
    {
      get
      {
        return _ContextInformation.IsMachineLevel;
      }
    }
    
    /// <summary>Provides an object containing configuration-section information based on the specified section name.</summary>
    /// <returns>An object containing the specified section within the configuration.</returns>
    /// <param name="sectionName">The name of the configuration section.</param>
    public object GetSection(string sectionName)
    {
      return _ContextInformation.GetSection(sectionName);
    }
  }
}
