//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Interfaces.Diagnostics
{
  
  
  /// <summary>Specifies a set of values that are used when you start a process.</summary>
  /// <filterpriority>2</filterpriority>
  public interface IProcessStartInfo
  {
    
    /// <summary>Provides access to the wrapped instance. Should not be used most of the time.</summary>
    System.Diagnostics.ProcessStartInfo _ProcessStartInfo
    {
      get;
    }
    
    string Verb
    {
      get;
      set;
    }
    
    string Arguments
    {
      get;
      set;
    }
    
    bool CreateNoWindow
    {
      get;
      set;
    }
    
    System.Collections.Specialized.StringDictionary EnvironmentVariables
    {
      get;
    }
    
    bool RedirectStandardInput
    {
      get;
      set;
    }
    
    bool RedirectStandardOutput
    {
      get;
      set;
    }
    
    bool RedirectStandardError
    {
      get;
      set;
    }
    
    System.Text.Encoding StandardErrorEncoding
    {
      get;
      set;
    }
    
    System.Text.Encoding StandardOutputEncoding
    {
      get;
      set;
    }
    
    bool UseShellExecute
    {
      get;
      set;
    }
    
    string[] Verbs
    {
      get;
    }
    
    string UserName
    {
      get;
      set;
    }
    
    System.Security.SecureString Password
    {
      get;
      set;
    }
    
    string Domain
    {
      get;
      set;
    }
    
    bool LoadUserProfile
    {
      get;
      set;
    }
    
    string FileName
    {
      get;
      set;
    }
    
    string WorkingDirectory
    {
      get;
      set;
    }
    
    bool ErrorDialog
    {
      get;
      set;
    }
    
    System.IntPtr ErrorDialogParentHandle
    {
      get;
      set;
    }
    
    System.Diagnostics.ProcessWindowStyle WindowStyle
    {
      get;
      set;
    }
  }
}
