//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Wrappers.Xml.Linq
{
  
  
  /// <summary>Represents an XML attribute.</summary>
  public partial class XAttributeWrapper : Wrapperator.Interfaces.Xml.Linq.IXAttribute
  {
    
    private System.Xml.Linq.XAttribute _xAttribute;
    
    public XAttributeWrapper(System.Xml.Linq.XAttribute xAttribute)
    {
      _xAttribute = xAttribute;
    }
    
    public System.Collections.Generic.IEnumerable<System.Xml.Linq.XAttribute> EmptySequence
    {
      get
      {
        return System.Xml.Linq.XAttribute.EmptySequence;
      }
    }
    
    public bool IsNamespaceDeclaration
    {
      get
      {
        return _xAttribute.IsNamespaceDeclaration;
      }
    }
    
    public System.Xml.Linq.XName Name
    {
      get
      {
        return _xAttribute.Name;
      }
    }
    
    public System.Xml.Linq.XAttribute NextAttribute
    {
      get
      {
        return _xAttribute.NextAttribute;
      }
    }
    
    public System.Xml.XmlNodeType NodeType
    {
      get
      {
        return _xAttribute.NodeType;
      }
    }
    
    public System.Xml.Linq.XAttribute PreviousAttribute
    {
      get
      {
        return _xAttribute.PreviousAttribute;
      }
    }
    
    public string Value
    {
      get
      {
        return _xAttribute.Value;
      }
      set
      {
        _xAttribute.Value = value;
      }
    }
    
    /// <summary>Removes this attribute from its parent element.</summary>
    /// <exception cref="T:System.InvalidOperationException">The parent element is null.</exception>
    public void Remove()
    {
      _xAttribute.Remove();
    }
    
    /// <summary>Sets the value of this attribute.</summary>
    /// <param name="value">The value to assign to this attribute.</param>
    /// <exception cref="T:System.ArgumentNullException">The <paramref name="value" /> parameter is null.</exception>
    /// <exception cref="T:System.ArgumentException">The <paramref name="value" /> is an <see cref="T:System.Xml.Linq.XObject" />.</exception>
    public void SetValue(object value)
    {
      _xAttribute.SetValue(value);
    }
  }
}
