//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Wrappers.Xml.Linq
{
  
  
  /// <summary>Represents an XML attribute.</summary>
  public partial class XAttributeWrapper : XObjectWrapper, Wrapperator.Interfaces.Xml.Linq.IXAttribute
  {
    
    private System.Xml.Linq.XAttribute _xAttribute;
    
    public XAttributeWrapper(System.Xml.Linq.XAttribute xAttribute) : 
        base(xAttribute)
    {
      _xAttribute = xAttribute;
    }
    
    public new string BaseUri
    {
      get
      {
        return _xAttribute.BaseUri;
      }
    }
    
    public new System.Xml.Linq.XDocument Document
    {
      get
      {
        return _xAttribute.Document;
      }
    }
    
    public System.Collections.Generic.IEnumerable<System.Xml.Linq.XAttribute> EmptySequence
    {
      get
      {
        return System.Xml.Linq.XAttribute.EmptySequence;
      }
    }
    
    public bool IsNamespaceDeclaration
    {
      get
      {
        return _xAttribute.IsNamespaceDeclaration;
      }
    }
    
    public System.Xml.Linq.XName Name
    {
      get
      {
        return _xAttribute.Name;
      }
    }
    
    public System.Xml.Linq.XAttribute NextAttribute
    {
      get
      {
        return _xAttribute.NextAttribute;
      }
    }
    
    public new System.Xml.XmlNodeType NodeType
    {
      get
      {
        return _xAttribute.NodeType;
      }
    }
    
    public new System.Xml.Linq.XElement Parent
    {
      get
      {
        return _xAttribute.Parent;
      }
    }
    
    public System.Xml.Linq.XAttribute PreviousAttribute
    {
      get
      {
        return _xAttribute.PreviousAttribute;
      }
    }
    
    public string Value
    {
      get
      {
        return _xAttribute.Value;
      }
      set
      {
        _xAttribute.Value = value;
      }
    }
    
    /// <summary>Adds an object to the annotation list of this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <param name="annotation">An <see cref="T:System.Object" /> that contains the annotation to add.</param>
    public new void AddAnnotation(object annotation)
    {
      _xAttribute.AddAnnotation(annotation);
    }
    
    /// <summary>Gets the first annotation object of the specified type from this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <returns>The <see cref="T:System.Object" /> that contains the first annotation object that matches the specified type, or null if no annotation is of the specified type.</returns>
    /// <param name="type">The <see cref="T:System.Type" /> of the annotation to retrieve.</param>
    public new object Annotation(System.Type type)
    {
      return _xAttribute.Annotation(type);
    }
    
    /// <summary>Get the first annotation object of the specified type from this <see cref="T:System.Xml.Linq.XObject" />. </summary>
    /// <returns>The first annotation object that matches the specified type, or null if no annotation is of the specified type.</returns>
    /// <typeparam name="T">The type of the annotation to retrieve.</typeparam>
    public new T Annotation<T>()
      where T :  class
    {
      return _xAttribute.Annotation<T>();
    }
    
    /// <summary>Gets a collection of annotations of the specified type for this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <returns>An <see cref="T:System.Collections.Generic.IEnumerable`1" /> of <see cref="T:System.Object" /> that contains the annotations that match the specified type for this <see cref="T:System.Xml.Linq.XObject" />.</returns>
    /// <param name="type">The <see cref="T:System.Type" /> of the annotations to retrieve.</param>
    public new System.Collections.Generic.IEnumerable<object> Annotations(System.Type type)
    {
      return _xAttribute.Annotations(type);
    }
    
    /// <summary>Gets a collection of annotations of the specified type for this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <returns>An <see cref="T:System.Collections.Generic.IEnumerable`1" /> that contains the annotations for this <see cref="T:System.Xml.Linq.XObject" />.</returns>
    /// <typeparam name="T">The type of the annotations to retrieve.</typeparam>
    public new System.Collections.Generic.IEnumerable<T> Annotations<T>()
      where T :  class
    {
      return _xAttribute.Annotations<T>();
    }
    
    /// <summary>Removes this attribute from its parent element.</summary>
    /// <exception cref="T:System.InvalidOperationException">The parent element is null.</exception>
    public void Remove()
    {
      _xAttribute.Remove();
    }
    
    /// <summary>Removes the annotations of the specified type from this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <param name="type">The <see cref="T:System.Type" /> of annotations to remove.</param>
    public new void RemoveAnnotations(System.Type type)
    {
      _xAttribute.RemoveAnnotations(type);
    }
    
    /// <summary>Removes the annotations of the specified type from this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <typeparam name="T">The type of annotations to remove.</typeparam>
    public new void RemoveAnnotations<T>()
      where T :  class
    {
      _xAttribute.RemoveAnnotations<T>();
    }
    
    /// <summary>Sets the value of this attribute.</summary>
    /// <param name="value">The value to assign to this attribute.</param>
    /// <exception cref="T:System.ArgumentNullException">The <paramref name="value" /> parameter is null.</exception>
    /// <exception cref="T:System.ArgumentException">The <paramref name="value" /> is an <see cref="T:System.Xml.Linq.XObject" />.</exception>
    public void SetValue(object value)
    {
      _xAttribute.SetValue(value);
    }
  }
}
