//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Wrappers.Xml.Linq
{
  
  
  /// <summary>Represents a text node that contains CDATA. </summary>
  public partial class XCDataWrapper : Wrapperator.Interfaces.Xml.Linq.IXCData
  {
    
    private System.Xml.Linq.XCData _xCData;
    
    public XCDataWrapper(System.Xml.Linq.XCData xCData)
    {
      _xCData = xCData;
    }
    
    /// <summary>Writes this CDATA object to an <see cref="T:System.Xml.XmlWriter" />.</summary>
    /// <param name="writer">An <see cref="T:System.Xml.XmlWriter" /> into which this method will write.</param>
    /// <filterpriority>2</filterpriority>
    public void WriteTo(System.Xml.XmlWriter writer)
    {
      _xCData.WriteTo(writer);
    }
  }
}
