//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Wrappers.Xml.Linq
{
  
  
  /// <summary>Represents a node or an attribute in an XML tree. </summary>
  /// <filterpriority>2</filterpriority>
  public partial class XObjectWrapper : Wrapperator.Interfaces.Xml.Linq.IXObject
  {
    
    private System.Xml.Linq.XObject _xObject;
    
    public static implicit operator System.Xml.Linq.XObject (XObjectWrapper wrapper)
    {
      if (wrapper == null) return default(System.Xml.Linq.XObject);
      return wrapper._xObject;
    }
    
    public XObjectWrapper(System.Xml.Linq.XObject xObject)
    {
      _xObject = xObject;
    }
    
    public string BaseUri
    {
      get
      {
        return _xObject.BaseUri;
      }
    }
    
    public System.Xml.Linq.XDocument Document
    {
      get
      {
        return _xObject.Document;
      }
    }
    
    public System.Xml.XmlNodeType NodeType
    {
      get
      {
        return _xObject.NodeType;
      }
    }
    
    public System.Xml.Linq.XElement Parent
    {
      get
      {
        return _xObject.Parent;
      }
    }
    
    /// <summary>Adds an object to the annotation list of this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <param name="annotation">An <see cref="T:System.Object" /> that contains the annotation to add.</param>
    public void AddAnnotation(object annotation)
    {
      _xObject.AddAnnotation(annotation);
    }
    
    /// <summary>Gets the first annotation object of the specified type from this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <returns>The <see cref="T:System.Object" /> that contains the first annotation object that matches the specified type, or null if no annotation is of the specified type.</returns>
    /// <param name="type">The <see cref="T:System.Type" /> of the annotation to retrieve.</param>
    public object Annotation(System.Type type)
    {
      return _xObject.Annotation(type);
    }
    
    /// <summary>Get the first annotation object of the specified type from this <see cref="T:System.Xml.Linq.XObject" />. </summary>
    /// <returns>The first annotation object that matches the specified type, or null if no annotation is of the specified type.</returns>
    /// <typeparam name="T">The type of the annotation to retrieve.</typeparam>
    public T Annotation<T>()
      where T :  class
    {
      return _xObject.Annotation<T>();
    }
    
    /// <summary>Gets a collection of annotations of the specified type for this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <returns>An <see cref="T:System.Collections.Generic.IEnumerable`1" /> of <see cref="T:System.Object" /> that contains the annotations that match the specified type for this <see cref="T:System.Xml.Linq.XObject" />.</returns>
    /// <param name="type">The <see cref="T:System.Type" /> of the annotations to retrieve.</param>
    public System.Collections.Generic.IEnumerable<object> Annotations(System.Type type)
    {
      return _xObject.Annotations(type);
    }
    
    /// <summary>Gets a collection of annotations of the specified type for this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <returns>An <see cref="T:System.Collections.Generic.IEnumerable`1" /> that contains the annotations for this <see cref="T:System.Xml.Linq.XObject" />.</returns>
    /// <typeparam name="T">The type of the annotations to retrieve.</typeparam>
    public System.Collections.Generic.IEnumerable<T> Annotations<T>()
      where T :  class
    {
      return _xObject.Annotations<T>();
    }
    
    /// <summary>Removes the annotations of the specified type from this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <param name="type">The <see cref="T:System.Type" /> of annotations to remove.</param>
    public void RemoveAnnotations(System.Type type)
    {
      _xObject.RemoveAnnotations(type);
    }
    
    /// <summary>Removes the annotations of the specified type from this <see cref="T:System.Xml.Linq.XObject" />.</summary>
    /// <typeparam name="T">The type of annotations to remove.</typeparam>
    public void RemoveAnnotations<T>()
      where T :  class
    {
      _xObject.RemoveAnnotations<T>();
    }
  }
}
