//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrapperator.Wrappers.Xml.Linq
{
  
  
  /// <summary>Represents an XML processing instruction. </summary>
  public partial class XProcessingInstructionWrapper : Wrapperator.Interfaces.Xml.Linq.IXProcessingInstruction
  {
    
    private System.Xml.Linq.XProcessingInstruction _xProcessingInstruction;
    
    public XProcessingInstructionWrapper(System.Xml.Linq.XProcessingInstruction xProcessingInstruction)
    {
      _xProcessingInstruction = xProcessingInstruction;
    }
    
    public string BaseUri
    {
      get
      {
        return _xProcessingInstruction.BaseUri;
      }
    }
    
    public string Data
    {
      get
      {
        return _xProcessingInstruction.Data;
      }
      set
      {
        _xProcessingInstruction.Data = value;
      }
    }
    
    public System.Xml.Linq.XDocument Document
    {
      get
      {
        return _xProcessingInstruction.Document;
      }
    }
    
    public System.Xml.Linq.XNode NextNode
    {
      get
      {
        return _xProcessingInstruction.NextNode;
      }
    }
    
    public System.Xml.XmlNodeType NodeType
    {
      get
      {
        return _xProcessingInstruction.NodeType;
      }
    }
    
    public System.Xml.Linq.XElement Parent
    {
      get
      {
        return _xProcessingInstruction.Parent;
      }
    }
    
    public System.Xml.Linq.XNode PreviousNode
    {
      get
      {
        return _xProcessingInstruction.PreviousNode;
      }
    }
    
    public string Target
    {
      get
      {
        return _xProcessingInstruction.Target;
      }
      set
      {
        _xProcessingInstruction.Target = value;
      }
    }
    
    /// <summary>Writes this processing instruction to an <see cref="T:System.Xml.XmlWriter" />.</summary>
    /// <param name="writer">The <see cref="T:System.Xml.XmlWriter" /> to write this processing instruction to.</param>
    /// <filterpriority>2</filterpriority>
    public void WriteTo(System.Xml.XmlWriter writer)
    {
      _xProcessingInstruction.WriteTo(writer);
    }
  }
}
